name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-nix:
    name: Lint Nix files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12

      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Check formatting with nixpkgs-fmt
        run: |
          set -euo pipefail
          NIX_FILES=$(git ls-files '*.nix' | tr '\n' ' ')
          if [ -n "$NIX_FILES" ]; then
            nix run --accept-flake-config nixpkgs#nixpkgs-fmt -- --check $NIX_FILES
          else
            echo "No .nix files to check"
          fi

  eval-linux:
    name: Evaluate flake (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12

      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Show flake outputs
        run: nix --accept-flake-config flake show

      - name: Evaluate darwin configuration toplevel attr
        run: |
          # Ensure the darwin system evaluates (no build)
          nix --accept-flake-config eval .#darwinConfigurations.icebook.config.system.build.toplevel.drvPath >/dev/null

  eval-macos:
    name: Evaluate flake (macOS)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12

      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Show flake outputs
        run: nix --accept-flake-config flake show

      - name: Evaluate darwin configuration toplevel attr
        run: |
          # Evaluate only to avoid cross-arch builds on GitHub runners
          nix --accept-flake-config eval .#darwinConfigurations.icebook.config.system.build.toplevel.drvPath >/dev/null

