name: Nix CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  nix-checks:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      # Install Nix
      - uses: DeterminateSystems/nix-installer-action@main

      # Enable binary cache (optional but recommended)
      - uses: DeterminateSystems/magic-nix-cache-action@main

      # Check that your flake evaluates and passes tests
      - name: Flake check
        run: nix flake check --print-build-logs

      # Build home-manager activation package for user mmf
      - name: Build home-manager config
        run: nix build .#homeConfigurations.mmf.activationPackage --print-build-logs

      # Build nix-darwin system config for host icebook
      - name: Build nix-darwin config
        run: nix build .#darwinConfigurations.icebook.system --print-build-logs
